# Generated by Django 2.0.5 on 2018-05-29 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('area', models.CharField(max_length=15)),
                ('party_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 23, 28, 45, 81719))),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20)),
                ('link', models.TextField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('author', models.TextField(max_length=20)),
                ('summary', models.TextField()),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 23, 28, 45, 81719))),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 23, 28, 45, 81719))),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 23, 28, 45, 81719))),
            ],
        ),
    ]
