# Generated by Django 2.0.4 on 2018-04-24 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 18, 53, 38, 376371))),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 18, 53, 38, 376371))),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 18, 53, 38, 376371)),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
