# Generated by Django 2.0.4 on 2018-06-03 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('keywords_id', models.TextField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=2)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 713413))),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 713413))),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 712433)),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 712433)),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 711451)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 3, 18, 19, 25, 711451)),
        ),
    ]
