# Generated by Django 2.0.4 on 2018-04-24 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_summary', '0003_auto_20180424_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 10, 6, 141789))),
            ],
        ),
        migrations.AlterField(
            model_name='keyword',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 10, 6, 141789)),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 10, 6, 141789)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 10, 6, 141789)),
        ),
    ]
