# Generated by Django 2.0.4 on 2018-04-24 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_summary', '0004_auto_20180424_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 12, 37, 947892)),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 12, 37, 947892)),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 12, 37, 947892)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 20, 12, 37, 947892)),
        ),
    ]
